version: "2"

services:
  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./logs/nginx:/var/log/nginx
    ports:
      - "80:80"
    networks:
      - internal
      - outside
    depends_on:
      - service
  service:
    build:
      context: ./
    ports:
      - "3000:3000"
    networks:
      - internal
      - outside
    volumes:
      - ./logs/service:/opt/tromazo/logs/service
    depends_on:
      - mysql
  mysql:
    image: mysql
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - internal
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: tromazo
    cap_add:
      - SYS_NICE

volumes:
  mysql_data: {}

networks:
  internal:
    internal: true
  outside:
    driver: bridge
